baseURL = "http://hugo.david.work/"
languageCode = "en-us"
title = "Hugo lives here"
theme = "gohugo-theme-ananke"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[taxonomies]
   tag = "tags"
   category = "categories"


[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://facebook.com/david9013"
  twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 3